version: "3.8"

services:

  db:
    container_name: postgresql_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - ./env_vars/postgres.env

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

  app:
    container_name: app
    build: .
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always
