"""change time fields

Revision ID: bc981401c1b1
Revises: b3f3bee1f9c3
Create Date: 2024-03-04 22:29:00.718687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc981401c1b1'
down_revision: Union[str, None] = 'b3f3bee1f9c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('completed_content_blocks', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('completed_content_blocks', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('content_blocks', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('content_blocks', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('courses', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('courses', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('profiles', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('profiles', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('sections', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('sections', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('student_courses', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('student_courses', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('student_courses', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('student_courses', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('sections', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('sections', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('profiles', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('profiles', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('courses', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('courses', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('content_blocks', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('content_blocks', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('completed_content_blocks', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('completed_content_blocks', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
